name: Build Solution

on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
  pull_request:
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Install SQL Server LocalDB
      run: |
        # VS Build Toolsインストーラーのダウンロード
        Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile vs_buildtools.exe
        
        # LocalDBを含むSQL Server開発ツールのインストール
        Start-Process -Wait -FilePath .\vs_buildtools.exe -ArgumentList `
          "--quiet", `
          "--wait", `
          "--norestart", `
          "--nocache", `
          "--installPath", "C:\BuildTools", `
          "--add", "Microsoft.VisualStudio.Workload.DataBuildTools", `
          "--add", "Microsoft.VisualStudio.Component.SQL.LocalDB.Runtime"
          
        # インストール確認
        Write-Host "Checking LocalDB installation..."
        $localDBPath = "C:\Program Files\Microsoft SQL Server\150\Tools\Binn\SqlLocalDB.exe"
        if (Test-Path $localDBPath) {
            & $localDBPath v
        } else {
            Write-Host "LocalDB executable not found at expected path"
            exit 1
        }
      shell: pwsh

    - name: Start LocalDB Instance
      run: |
        sqllocaldb start MSSQLLocalDB
        sqllocaldb info MSSQLLocalDB
      shell: pwsh

    - name: Test LocalDB Connection
      run: |
        $connectionString = "Server=(localdb)\MSSQLLocalDB;Database=master;Integrated Security=True"
        $maxAttempts = 3
        $attempt = 0
        $success = $false
        
        while ($attempt -lt $maxAttempts -and -not $success) {
            $attempt++
            try {
                $connection = New-Object System.Data.SqlClient.SqlConnection($connectionString)
                $command = New-Object System.Data.SqlClient.SqlCommand("SELECT @@VERSION", $connection)
                
                $connection.Open()
                $result = $command.ExecuteScalar()
                Write-Host "SQL Server Version: $result"
                Write-Host "Connection test successful!"
                $success = $true
            }
            catch {
                Write-Host "Attempt $attempt failed: $_"
                if ($attempt -lt $maxAttempts) {
                    Write-Host "Waiting before retry..."
                    Start-Sleep -Seconds 5
                }
            }
            finally {
                if ($connection) {
                    $connection.Close()
                }
            }
        }
        
        if (-not $success) {
            Write-Host "Failed to connect to LocalDB after $maxAttempts attempts"
            sqllocaldb info MSSQLLocalDB
            exit 1
        }
      shell: pwsh

    - name: Create Test Database
      run: |
        $connectionString = "Server=(localdb)\MSSQLLocalDB;Database=master;Integrated Security=True"
        $createDbQuery = "
        IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'TestDB')
        BEGIN
            CREATE DATABASE TestDB;
        END
        "
        
        $connection = New-Object System.Data.SqlClient.SqlConnection($connectionString)
        $command = New-Object System.Data.SqlClient.SqlCommand($createDbQuery, $connection)
        
        try {
            $connection.Open()
            $command.ExecuteNonQuery()
            Write-Host "TestDB database created successfully!"
        }
        catch {
            Write-Host "Error creating database: $_"
            sqllocaldb info MSSQLLocalDB
            exit 1
        }
        finally {
            $connection.Close()
        }
      shell: pwsh

    - name: Restore dependencies
      run: dotnet restore src/SqlBulkCopier.sln

    - name: Build solution
      run: dotnet build src/SqlBulkCopier.sln --configuration Release --no-restore